---
# tasks file for rsync (CentOS specific)

- name: Install rsync packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ rsync_packages }}"
  tags:
    - rsync
