---
# tasks file for rsync

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - rsync

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags:
    - rsync

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - rsync
