---
# tasks file for rsync (Ubuntu specific)

- name: Install rsync packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ rsync_packages }}"
  tags:
    - rsync
